spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/musicDB
      username: postgres
      password: Harmony_love04

  flyway:

    locations: classpath:db/migration
    table: schema_version


server:
  error:
    include-binding-errors: always
    include-message: always


